export enum Features {
  INTENSITY = "INTENSITY",
  CALORIES_BURNED = "CALORIES_BURNED",
  BODY_MUSCLE_GROUP = "BODY_MUSCLE_GROUP",
  BURNER_SCORE = "BURNER_SCORE",
  IRON_SCORE = "IRON_SCORE",
  MUSCLE_GROUP_REPS_COUNT = "MUSCLE_GROUP_REPS_COUNT",
  YOGA_POSE_ALIGNMENT_SCORE = "YOGA_POSE_ALIGNMENT_SCORE",
  YOGA_POSE_GROUP = "YOGA_POSE_GROUP",
  YOGA_TOTAL_POSES = "YOGA_TOTAL_POSES",
  YOGA_QUALITY = "YOGA_QUALITY",
  YOGA_SCORE = "YOGA_SCORE",
  VORTEX = "VORTEX",
  REPS = "REPS",
  CORRECTIVE_FEEDBACK = "CORRECTIVE_FEEDBACK",
}

export enum ClassCategory {
  Yoga = "Yoga",
  Strength = "Strength",
  HIIT = "HIIT",
}

export enum Assessment {
  STRENGTH_PUSH_UPS = 'STRENGTH_PUSH_UPS',
  HALF_SQUAT = 'HALF_SQUAT'
  // 2 more
}
